package com.ruitong.huiyi3.beans;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HUAN_YIN_YU_BEAN".
*/
public class HuanYinYuBeanDao extends AbstractDao<HuanYinYuBean, Long> {

    public static final String TABLENAME = "HUAN_YIN_YU_BEAN";

    /**
     * Properties of entity HuanYinYuBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Huanyinci = new Property(2, String.class, "huanyinci", false, "HUANYINCI");
        public final static Property Bianhao = new Property(3, int.class, "bianhao", false, "BIANHAO");
    }


    public HuanYinYuBeanDao(DaoConfig config) {
        super(config);
    }
    
    public HuanYinYuBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HUAN_YIN_YU_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"HUANYINCI\" TEXT," + // 2: huanyinci
                "\"BIANHAO\" INTEGER NOT NULL );"); // 3: bianhao
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HUAN_YIN_YU_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, HuanYinYuBean entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String huanyinci = entity.getHuanyinci();
        if (huanyinci != null) {
            stmt.bindString(3, huanyinci);
        }
        stmt.bindLong(4, entity.getBianhao());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, HuanYinYuBean entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String huanyinci = entity.getHuanyinci();
        if (huanyinci != null) {
            stmt.bindString(3, huanyinci);
        }
        stmt.bindLong(4, entity.getBianhao());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public HuanYinYuBean readEntity(Cursor cursor, int offset) {
        HuanYinYuBean entity = new HuanYinYuBean( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // huanyinci
            cursor.getInt(offset + 3) // bianhao
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, HuanYinYuBean entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setHuanyinci(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setBianhao(cursor.getInt(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(HuanYinYuBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(HuanYinYuBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(HuanYinYuBean entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
